apiVersion: apps/v1
kind: Deployment
metadata:
  name: up-service
spec:
  selector:
    matchLabels:
      app: up-service
  replicas: 2
  template:
    metadata:
      labels:
        app: up-service
    spec:
      containers:
        - name: up-service
          image: danielgershmandev/argocd-app:1.2
          ports:
            - containerPort: 8080
